#!/usr/bin/env bash
# This script will create the bootstrapping tarball that packages need
# to use npm3. This means we don't need to store a binary tarball in
# source control.
#
# Usage:
# $ ./gen_npm3      # Generate in a temporary directory
# $ TMPDIR=/path/to/tmpdir ./gen_npm3

set -e

[[ -z $TMPDIR ]] && export TMPDIR=/tmp
OUTPUT=$(mktemp -d $TMPDIR/gen-npm3-XXXX)

[[ -z $NIXFROMNPM ]] && {
  # CD into the directory of this file and echo the current directory.
  _current_path=$(cd $(dirname $0); pwd)
  # Then set the NIXFROMNPM folder to be that directory's parent.
  export NIXFROMNPM=$(dirname $_current_path)
}

TARBALL=$NIXFROMNPM/nix-libs/nodeLib/npm3.tar.gz

fetch_npm3_nix() {
  # Generate output with nixfromnpm
  nix-shell $NIXFROMNPM --command "cabal run -- -p npm -o $OUTPUT"
}

# Do a dry-run build to make sure everything will work
test_npm3_works() {
  nix-build $OUTPUT \
    -A nodePackages.npm \
    --arg npm3 false \
    --dry-run
}

# Create the npm3.tar.gz
gen_npm3_tarball() (
  cd $OUTPUT && tar -cf $TARBALL \
    --exclude=./nodeLib/npm3.tar.gz \
    .
)

echo "Fetching package definitions in $OUTPUT..."
fetch_npm3_nix
echo "Testing dependencies are satisfied..."
test_npm3_works
echo "Generating tarball in $TARBALL..."
gen_npm3_tarball
echo "Done! Tarball is in $TARBALL"
rm -rf $OUTPUT
